/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m7_3;

import javax.swing.JOptionPane;

/**
 *
 * @author Arddhana Zhafran
 */
public class Frame3 extends javax.swing.JFrame {

    /**
     * Creates new form Frame3
     */
    public Frame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etTinggi = new javax.swing.JTextField();
        etPanjang = new javax.swing.JTextField();
        etLebar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btHitung = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        etSisi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btHitungK = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        etJari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btHitungB = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("PROGRAM PENCARI VOLUME BANGUN RUANG");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 0, 510, 50);

        jPanel2.setLayout(null);

        jLabel2.setText("TINGGI");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 109, 66, 32);

        jLabel3.setText("PANJANG");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 33, 66, 32);

        jLabel4.setText("LEBAR");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 71, 66, 32);

        etTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etTinggiActionPerformed(evt);
            }
        });
        jPanel2.add(etTinggi);
        etTinggi.setBounds(90, 110, 208, 32);
        jPanel2.add(etPanjang);
        etPanjang.setBounds(90, 30, 208, 32);
        jPanel2.add(etLebar);
        etLebar.setBounds(90, 70, 208, 32);

        jLabel5.setText("CM");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(320, 30, 66, 32);

        jLabel6.setText("CM");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(320, 70, 66, 32);

        jLabel7.setText("CM");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(320, 110, 66, 32);

        btHitung.setText("HITUNG");
        btHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHitungActionPerformed(evt);
            }
        });
        jPanel2.add(btHitung);
        btHitung.setBounds(90, 160, 100, 40);

        jTabbedPane1.addTab("Balok", jPanel2);

        jPanel3.setLayout(null);

        jLabel8.setText("SISI");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 33, 66, 32);
        jPanel3.add(etSisi);
        etSisi.setBounds(90, 30, 208, 32);

        jLabel9.setText("CM");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(320, 30, 66, 32);

        btHitungK.setText("HITUNG");
        btHitungK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHitungKActionPerformed(evt);
            }
        });
        jPanel3.add(btHitungK);
        btHitungK.setBounds(90, 160, 100, 40);

        jTabbedPane1.addTab("Kubus", jPanel3);

        jPanel4.setLayout(null);

        jLabel10.setText("JARI_JARI");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(20, 30, 66, 32);
        jPanel4.add(etJari);
        etJari.setBounds(90, 30, 208, 32);

        jLabel11.setText("CM");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(320, 30, 66, 32);

        btHitungB.setText("HITUNG");
        btHitungB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHitungBActionPerformed(evt);
            }
        });
        jPanel4.add(btHitungB);
        btHitungB.setBounds(90, 160, 100, 40);

        jTabbedPane1.addTab("Bola", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 50, 620, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etTinggiActionPerformed

    private void btHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHitungActionPerformed
      int panjang, lebar, tinggi;
      panjang = Integer.parseInt(etPanjang.getText());
      lebar = Integer.parseInt(etLebar.getText());
      tinggi = Integer.parseInt(etTinggi.getText());
      
      int hasil = panjang*lebar*tinggi;
      try{
          JOptionPane.showMessageDialog(null,"Volume Balok Adalah :"+hasil,"luas",
                  JOptionPane.INFORMATION_MESSAGE);
      } catch(Exception e){
          JOptionPane.showMessageDialog(null,"Error: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
      }
    }//GEN-LAST:event_btHitungActionPerformed

    private void btHitungKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHitungKActionPerformed
      int sisi;
      sisi = Integer.parseInt(etSisi.getText());
      int hasil=sisi*sisi*sisi;
      
      try{
          JOptionPane.showMessageDialog(null,"Volume Kubus Adalah "+hasil,
                  "luas",JOptionPane.INFORMATION_MESSAGE);
      } catch(Exception e){
          JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                  JOptionPane.WARNING_MESSAGE);
      }
    }//GEN-LAST:event_btHitungKActionPerformed

    private void btHitungBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHitungBActionPerformed
       float jari;
       jari=Integer.parseInt(etJari.getText());
       float hasil = (float) (4/3*3.14*jari*jari*jari);
       try{
           JOptionPane.showMessageDialog(null,"Volume Bola Adalah "+hasil,
                   "luas",JOptionPane.INFORMATION_MESSAGE);
       } catch (Exception e){
           JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                   JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_btHitungBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHitung;
    private javax.swing.JButton btHitungB;
    private javax.swing.JButton btHitungK;
    private javax.swing.JTextField etJari;
    private javax.swing.JTextField etLebar;
    private javax.swing.JTextField etPanjang;
    private javax.swing.JTextField etSisi;
    private javax.swing.JTextField etTinggi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
